import { StorySpec } from './storySpec';

/**
 * Grade 1, appended after the six stories that opened the map.
 *
 * Short sentences, one idea at a time, and a paragraph that resolves — a
 * six-year-old should be able to hold the whole thing in their head at once.
 * Distractors are drawn from the story's own furniture, so picking one means
 * misreading rather than guessing wildly.
 */
export const GRADE_1: StorySpec[] = [
  {
    title: 'The Paper Boat',
    icon: '⛵',
    text: `Sam folded a paper boat and set it in the gutter after the rain. The water carried it past three houses. It spun once at the corner and kept going. Sam ran beside it the whole way. Then the boat slipped into a drain and was gone.`,
    questions: [
      {
        id: 'q1',
        prompt: 'Where did Sam put his boat?',
        answer: 'In the gutter',
        distractors: ['In a pond', 'In the bath', 'In a bucket'],
        explanation: 'The first sentence says he set it in the gutter after the rain.',
        skill: 'detail',
      },
      {
        id: 'q2',
        prompt: 'What happened to the boat at the end?',
        answer: 'It went into a drain',
        distractors: ['It sank', 'Sam caught it', 'It came apart'],
        explanation: 'The last sentence says the boat slipped into a drain and was gone.',
        skill: 'sequence',
      },
      {
        id: 'q3',
        prompt: 'Why did Sam run beside the boat?',
        answer: 'He wanted to watch where it went',
        distractors: ['He was late', 'He was cold', 'He was chasing a dog'],
        explanation: 'He ran beside it the whole way, so he was following his boat.',
        skill: 'inference',
      },
    ],
  },
  {
    title: 'The Loose Tooth',
    icon: '🦷',
    text: `Ada had a loose tooth at the front. She wiggled it all through lunch. It would not come out. Then she bit into an apple and felt a small pop. The tooth was stuck in the apple. Ada laughed and showed everyone the gap.`,
    questions: [
      {
        id: 'q1',
        prompt: 'What finally pulled the tooth out?',
        answer: 'Biting an apple',
        distractors: ['Wiggling it', 'A string', 'The nurse'],
        explanation: 'She bit into an apple and felt a small pop, and the tooth was in the apple.',
        skill: 'sequence',
      },
      {
        id: 'q2',
        prompt: 'Where was the loose tooth?',
        answer: 'At the front',
        distractors: ['At the back', 'On the bottom left', 'Beside her tongue'],
        explanation: 'The story says Ada had a loose tooth at the front.',
        skill: 'detail',
      },
      {
        id: 'q3',
        prompt: 'How did Ada feel when the tooth came out?',
        answer: 'Pleased',
        distractors: ['Frightened', 'Angry', 'Bored'],
        explanation: 'She laughed and showed everyone the gap.',
        skill: 'inference',
      },
    ],
  },
  {
    title: 'Snail Race',
    icon: '🐌',
    text: `Theo found two snails on the wet path. He put them side by side on a flat stone. One snail went straight ahead. The other turned and climbed down the side of the stone. Theo waited a long time. The straight snail won.`,
    questions: [
      {
        id: 'q1',
        prompt: 'Where did Theo find the snails?',
        answer: 'On the wet path',
        distractors: ['On a flat stone', 'Under a leaf', 'In the grass'],
        explanation: 'The first sentence says he found two snails on the wet path.',
        skill: 'detail',
      },
      {
        id: 'q2',
        prompt: 'What did the second snail do?',
        answer: 'It climbed down the side',
        distractors: ['It went straight', 'It went to sleep', 'It hid in its shell'],
        explanation: 'The other snail turned and climbed down the side of the stone.',
        skill: 'detail',
      },
      {
        id: 'q3',
        prompt: 'Why did Theo have to wait a long time?',
        answer: 'Snails move slowly',
        distractors: ['It got dark', 'The snails were asleep', 'The stone was big'],
        explanation: 'A race between snails takes a long time because snails are slow.',
        skill: 'inference',
      },
    ],
  },
  {
    title: 'Bread for the Ducks',
    icon: '🦆',
    text: `Rosa took a bag of oats to the pond. Her mum said bread is bad for ducks. The ducks came fast when they saw the bag. Rosa threw the oats wide so the small ducks could eat too. One brown duck ate from her hand.`,
    questions: [
      {
        id: 'q1',
        prompt: 'What did Rosa bring to the pond?',
        answer: 'A bag of oats',
        distractors: ['A bag of bread', 'A bag of seeds', 'A bag of rice'],
        explanation: 'The first sentence says she took a bag of oats.',
        skill: 'detail',
      },
      {
        id: 'q2',
        prompt: 'Why did Rosa throw the oats wide?',
        answer: 'So the small ducks could eat too',
        distractors: ['To make them fly', 'Because the bag was full', 'To reach the far side'],
        explanation: 'The story says she threw them wide so the small ducks could eat too.',
        skill: 'detail',
      },
      {
        id: 'q3',
        prompt: 'Why did Rosa not bring bread?',
        answer: 'Her mum said it is bad for ducks',
        distractors: ['There was none left', 'Ducks do not like it', 'She forgot it'],
        explanation: 'Her mum said bread is bad for ducks, so Rosa brought oats instead.',
        skill: 'inference',
      },
    ],
  },
  {
    title: 'The Wobbly Chair',
    icon: '🪑',
    text: `The blue chair in the kitchen wobbled. Dad turned it over and looked underneath. One leg was shorter than the rest. He cut a small square of card and taped it to the short leg. Now the chair stands still, and nobody rocks at dinner.`,
    questions: [
      {
        id: 'q1',
        prompt: 'What was wrong with the chair?',
        answer: 'One leg was too short',
        distractors: ['A leg was broken', 'The seat was cracked', 'It had only three legs'],
        explanation: 'Dad looked underneath and one leg was shorter than the rest.',
        skill: 'detail',
      },
      {
        id: 'q2',
        prompt: 'What did Dad use to fix it?',
        answer: 'A square of card',
        distractors: ['A new leg', 'A nail', 'A piece of wood'],
        explanation: 'He cut a small square of card and taped it to the short leg.',
        skill: 'detail',
      },
      {
        id: 'q3',
        prompt: 'What is the story mostly about?',
        answer: 'Fixing a wobbly chair',
        distractors: ['Eating dinner', 'Painting a chair', 'Buying furniture'],
        explanation: 'Every sentence is about finding the problem and mending the chair.',
        skill: 'mainIdea',
      },
    ],
  },
  {
    title: 'Kite in the Tree',
    icon: '🪁',
    text: `Omar flew his kite in the field until the wind dropped. The kite fell into the top of an old tree. Omar could not reach it. His sister brought a long stick from the shed. Together they poked the kite until it slid free.`,
    questions: [
      {
        id: 'q1',
        prompt: 'Why did the kite fall?',
        answer: 'The wind dropped',
        distractors: ['The string broke', 'It hit a bird', 'Omar let go'],
        explanation: 'He flew it until the wind dropped, and then it fell into the tree.',
        skill: 'inference',
      },
      {
        id: 'q2',
        prompt: 'Who brought the stick?',
        answer: 'His sister',
        distractors: ['His dad', 'A neighbour', 'Omar himself'],
        explanation: 'The story says his sister brought a long stick from the shed.',
        skill: 'detail',
      },
      {
        id: 'q3',
        prompt: 'What happened last?',
        answer: 'The kite slid free',
        distractors: ['The kite fell', 'The wind dropped', 'The stick was fetched'],
        explanation: 'The last sentence says they poked until the kite slid free.',
        skill: 'sequence',
      },
    ],
  },
  {
    title: 'The Cold Puddle',
    icon: '🧊',
    text: `On Monday there was a puddle by the gate. On Tuesday it was hard and white. Lily tapped it with her boot and it cracked like a plate. Under the ice there was still water. By the afternoon the puddle was soft again.`,
    questions: [
      {
        id: 'q1',
        prompt: 'What had happened to the puddle by Tuesday?',
        answer: 'It had frozen',
        distractors: ['It had dried up', 'It had grown', 'It had turned muddy'],
        explanation: 'On Tuesday it was hard and white, and it cracked like a plate.',
        skill: 'inference',
      },
      {
        id: 'q2',
        prompt: 'What was under the ice?',
        answer: 'Water',
        distractors: ['Mud', 'Leaves', 'Stones'],
        explanation: 'The story says under the ice there was still water.',
        skill: 'detail',
      },
      {
        id: 'q3',
        prompt: 'Why was the puddle soft again by the afternoon?',
        answer: 'It had warmed up',
        distractors: ['It rained', 'Lily broke it all', 'Someone swept it'],
        explanation: 'Ice turns back to water when the day warms up.',
        skill: 'inference',
      },
    ],
  },
  {
    title: 'Grandpa\'s Whistle',
    icon: '😗',
    text: `Grandpa can whistle so loudly that the dog comes running from the far field. Jo tried all summer. She blew and blew and only air came out. Then one morning at the sink a small clear note came. The dog looked up at once.`,
    questions: [
      {
        id: 'q1',
        prompt: 'How do we know Jo finally whistled?',
        answer: 'The dog looked up',
        distractors: ['Grandpa clapped', 'She heard nothing', 'The dog ran away'],
        explanation: 'A clear note came and the dog looked up at once, just as it does for Grandpa.',
        skill: 'inference',
      },
      {
        id: 'q2',
        prompt: 'How long had Jo been trying?',
        answer: 'All summer',
        distractors: ['One morning', 'A week', 'Two years'],
        explanation: 'The story says Jo tried all summer.',
        skill: 'detail',
      },
      {
        id: 'q3',
        prompt: 'Where was Jo when it worked?',
        answer: 'At the sink',
        distractors: ['In the far field', 'In the garden', 'On the step'],
        explanation: 'The story says one morning at the sink a small clear note came.',
        skill: 'detail',
      },
    ],
  },
  {
    title: 'The Last Seat',
    icon: '🚌',
    text: `The bus was full. Only one seat was left, near the back. Kai walked towards it and saw an old man with two heavy bags behind him. Kai stopped and pointed at the seat. The man sat down and said thank you twice.`,
    questions: [
      {
        id: 'q1',
        prompt: 'Why did Kai stop walking?',
        answer: 'He saw the old man needed the seat',
        distractors: ['The bus braked', 'He forgot his ticket', 'The seat was wet'],
        explanation: 'He saw a man with two heavy bags and pointed him to the seat instead.',
        skill: 'inference',
      },
      {
        id: 'q2',
        prompt: 'Where was the empty seat?',
        answer: 'Near the back',
        distractors: ['At the front', 'By the driver', 'Upstairs'],
        explanation: 'The story says only one seat was left, near the back.',
        skill: 'detail',
      },
      {
        id: 'q3',
        prompt: 'What is this story mostly about?',
        answer: 'Being kind to someone',
        distractors: ['Riding a bus', 'Carrying bags', 'Getting to school'],
        explanation: 'The whole paragraph builds to Kai giving up the seat he wanted.',
        skill: 'mainIdea',
      },
    ],
  },
  {
    title: 'Too Much Salt',
    icon: '🧂',
    text: `Nell helped make the soup. She poured in salt while her dad answered the door. When they tasted it, both of them pulled a face. Dad added a potato and more water. They waited. The second taste was much better.`,
    questions: [
      {
        id: 'q1',
        prompt: 'What went wrong with the soup?',
        answer: 'There was too much salt',
        distractors: ['It was burnt', 'It was cold', 'It had no salt'],
        explanation: 'Nell poured in salt while Dad was away, and they both pulled a face.',
        skill: 'inference',
      },
      {
        id: 'q2',
        prompt: 'What did Dad add to help?',
        answer: 'A potato and more water',
        distractors: ['Sugar', 'More salt', 'Butter and bread'],
        explanation: 'The story says Dad added a potato and more water.',
        skill: 'detail',
      },
      {
        id: 'q3',
        prompt: 'What happened last?',
        answer: 'The soup tasted better',
        distractors: ['Nell poured the salt', 'Dad went to the door', 'They pulled a face'],
        explanation: 'The last sentence says the second taste was much better.',
        skill: 'sequence',
      },
    ],
  },
  {
    title: 'The Shell with a Hole',
    icon: '🐚',
    text: `Ivy filled her pockets with shells at the beach. Most were plain white. One had a small round hole near the top. Her aunt showed her how to thread it on a string. Now Ivy wears the shell that nobody else has.`,
    questions: [
      {
        id: 'q1',
        prompt: 'What made one shell special?',
        answer: 'It had a small hole',
        distractors: ['It was pink', 'It was the biggest', 'It was cracked'],
        explanation: 'One shell had a small round hole near the top, so it could be threaded.',
        skill: 'detail',
      },
      {
        id: 'q2',
        prompt: 'Why did the hole matter?',
        answer: 'A string could go through it',
        distractors: ['It made a sound', 'It held water', 'It was lighter'],
        explanation: 'Her aunt showed her how to thread it on a string because of the hole.',
        skill: 'inference',
      },
      {
        id: 'q3',
        prompt: 'Who helped Ivy?',
        answer: 'Her aunt',
        distractors: ['Her mum', 'Her brother', 'A shopkeeper'],
        explanation: 'The story says her aunt showed her how to thread it.',
        skill: 'detail',
      },
    ],
  },
  {
    title: 'Four Books',
    icon: '📚',
    text: `Milo got his own library card on Saturday. It had his name printed along the bottom. He was allowed to choose four books. He picked three about sharks and one about space. He read the space one first, in the car.`,
    questions: [
      {
        id: 'q1',
        prompt: 'How many books could Milo choose?',
        answer: 'Four',
        distractors: ['Three', 'One', 'Ten'],
        explanation: 'The story says he was allowed to choose four books.',
        skill: 'detail',
      },
      {
        id: 'q2',
        prompt: 'Which book did he read first?',
        answer: 'The one about space',
        distractors: ['A shark book', 'The thickest one', 'None of them'],
        explanation: 'He read the space one first, in the car.',
        skill: 'sequence',
      },
      {
        id: 'q3',
        prompt: 'What does Milo like best?',
        answer: 'Sharks',
        distractors: ['Cars', 'Cooking', 'Music'],
        explanation: 'Three of his four books were about sharks.',
        skill: 'inference',
      },
    ],
  },
  {
    title: 'A Nest in the Gutter',
    icon: '🐦',
    text: `Two birds carried grass to the gutter above the door. Dad wanted to clear it away. Mum said to wait until the young birds could fly. All spring the family used the back door instead. In June the nest went quiet.`,
    questions: [
      {
        id: 'q1',
        prompt: 'Why did the family use the back door?',
        answer: 'To leave the nest in peace',
        distractors: ['The front door broke', 'It was raining', 'The gutter fell'],
        explanation: 'They waited for the young birds to fly, so they stopped using that door.',
        skill: 'inference',
      },
      {
        id: 'q2',
        prompt: 'What did the birds carry?',
        answer: 'Grass',
        distractors: ['Sticks', 'Feathers', 'Mud'],
        explanation: 'The story says two birds carried grass to the gutter.',
        skill: 'detail',
      },
      {
        id: 'q3',
        prompt: 'Why did the nest go quiet in June?',
        answer: 'The young birds had gone',
        distractors: ['It rained', 'Dad cleared it', 'The birds were asleep'],
        explanation: 'They waited until the young birds could fly, and by June they had.',
        skill: 'inference',
      },
    ],
  },
  {
    title: 'The Wrong Shoes',
    icon: '👟',
    text: `Ben pulled his shoes on in a hurry. All morning his feet hurt. At playtime he looked down properly. The left shoe was on the right foot. He swapped them over on the step and ran off to play.`,
    questions: [
      {
        id: 'q1',
        prompt: 'Why did Ben\'s feet hurt?',
        answer: 'His shoes were on the wrong feet',
        distractors: ['The shoes were too small', 'He had a stone in one', 'He had run too far'],
        explanation: 'He looked down and the left shoe was on the right foot.',
        skill: 'inference',
      },
      {
        id: 'q2',
        prompt: 'When did Ben notice?',
        answer: 'At playtime',
        distractors: ['At breakfast', 'On the bus', 'At bedtime'],
        explanation: 'The story says at playtime he looked down properly.',
        skill: 'detail',
      },
      {
        id: 'q3',
        prompt: 'Why did Ben not notice sooner?',
        answer: 'He dressed in a hurry',
        distractors: ['It was dark', 'He had no socks', 'The shoes were new'],
        explanation: 'The first sentence says he pulled his shoes on in a hurry.',
        skill: 'inference',
      },
    ],
  },
  {
    title: 'The Tallest Sunflower',
    icon: '🌻',
    text: `Every child in the class planted one sunflower seed in a pot. Amir put his on the window sill in the sun. Others left theirs by the back wall. By July Amir\'s flower was taller than he was. The shady ones stayed small.`,
    questions: [
      {
        id: 'q1',
        prompt: 'Where did Amir put his pot?',
        answer: 'On the sunny window sill',
        distractors: ['By the back wall', 'Under a bench', 'In a cupboard'],
        explanation: 'The story says Amir put his on the window sill in the sun.',
        skill: 'detail',
      },
      {
        id: 'q2',
        prompt: 'Why did Amir\'s sunflower grow tallest?',
        answer: 'It got the most sunlight',
        distractors: ['It was watered more', 'It had a bigger pot', 'It was planted first'],
        explanation: 'His was in the sun and the ones in the shade stayed small.',
        skill: 'inference',
      },
      {
        id: 'q3',
        prompt: 'What is this story mostly about?',
        answer: 'Plants need light to grow',
        distractors: ['How to plant seeds', 'A class competition', 'Summer weather'],
        explanation: 'The sunny plant grew tall and the shady ones did not, which is the point.',
        skill: 'mainIdea',
      },
    ],
  },
  {
    title: 'The Puppet Show',
    icon: '🎭',
    text: `Zara made a stage from a big box and cut a window in the front. Her puppets were two socks with button eyes. She put on a show for her gran. Gran clapped so hard that one button came loose.`,
    questions: [
      {
        id: 'q1',
        prompt: 'What were the puppets made from?',
        answer: 'Socks',
        distractors: ['Paper bags', 'Wooden spoons', 'Old gloves'],
        explanation: 'The story says her puppets were two socks with button eyes.',
        skill: 'detail',
      },
      {
        id: 'q2',
        prompt: 'What did Zara use to make the stage?',
        answer: 'A big box',
        distractors: ['A table', 'A blanket', 'Two chairs'],
        explanation: 'She made a stage from a big box and cut a window in the front.',
        skill: 'detail',
      },
      {
        id: 'q3',
        prompt: 'What does the clapping tell us about Gran?',
        answer: 'She enjoyed the show',
        distractors: ['She was cold', 'She was leaving', 'She could not see'],
        explanation: 'She clapped so hard a button came loose, so she liked it very much.',
        skill: 'inference',
      },
    ],
  },
  {
    title: 'Rain on the Tent',
    icon: '⛺',
    text: `The rain started after dark. It tapped on the tent all night, loud and close. Freya could not sleep at first. Then the sound turned into something steady, like a drum far away. In the morning the field was full of puddles.`,
    questions: [
      {
        id: 'q1',
        prompt: 'When did the rain start?',
        answer: 'After dark',
        distractors: ['At breakfast', 'In the afternoon', 'At sunrise'],
        explanation: 'The first sentence says the rain started after dark.',
        skill: 'detail',
      },
      {
        id: 'q2',
        prompt: 'What is the rain compared to?',
        answer: 'A drum far away',
        distractors: ['A bell', 'Footsteps', 'A river'],
        explanation: 'The sound turned into something steady, like a drum far away.',
        skill: 'vocabulary',
      },
      {
        id: 'q3',
        prompt: 'How did Freya feel by the end of the night?',
        answer: 'Calmer',
        distractors: ['More afraid', 'Angry', 'Hungry'],
        explanation: 'At first she could not sleep, then the sound became steady and soothing.',
        skill: 'inference',
      },
    ],
  },
  {
    title: 'The Lost Glove Tree',
    icon: '🧤',
    text: `On the way to the park there is a fence with lost gloves on the posts. People find them on the path and leave them there. Some have been out all winter. Last week a woman took one back. It was her son\'s.`,
    questions: [
      {
        id: 'q1',
        prompt: 'Why do people put gloves on the posts?',
        answer: 'So the owner can find them',
        distractors: ['To dry them out', 'To decorate the fence', 'To keep the posts warm'],
        explanation: 'People find them on the path and leave them there, and a woman came back for one.',
        skill: 'inference',
      },
      {
        id: 'q2',
        prompt: 'Where is the fence?',
        answer: 'On the way to the park',
        distractors: ['Outside the school', 'Beside the shop', 'By the river'],
        explanation: 'The first sentence says it is on the way to the park.',
        skill: 'detail',
      },
      {
        id: 'q3',
        prompt: 'Who took a glove back last week?',
        answer: 'A woman',
        distractors: ['A boy', 'The park keeper', 'A postman'],
        explanation: 'The story says last week a woman took one back, and it was her son\'s.',
        skill: 'detail',
      },
    ],
  },
  {
    title: 'The Bike with No Pedals',
    icon: '🚲',
    text: `Sasha\'s first bike had no pedals at all. She pushed it along with her feet and lifted them up to glide. After two weeks she could glide the whole length of the path. Then Dad fitted the pedals. She rode away the same afternoon.`,
    questions: [
      {
        id: 'q1',
        prompt: 'What was missing from the bike at first?',
        answer: 'The pedals',
        distractors: ['The seat', 'One wheel', 'The handlebars'],
        explanation: 'The first sentence says her first bike had no pedals at all.',
        skill: 'detail',
      },
      {
        id: 'q2',
        prompt: 'Why could Sasha ride away so quickly?',
        answer: 'She had already learned to balance',
        distractors: ['The bike was new', 'Dad held the seat', 'The path was flat'],
        explanation: 'She had spent two weeks gliding, which is the balancing part.',
        skill: 'inference',
      },
      {
        id: 'q3',
        prompt: 'What does "glide" mean here?',
        answer: 'Roll along without pushing',
        distractors: ['Fall over', 'Pedal fast', 'Walk beside it'],
        explanation: 'She lifted her feet up to glide, so the bike rolled on by itself.',
        skill: 'vocabulary',
      },
    ],
  },
  {
    title: 'The Melting Cone',
    icon: '🍦',
    text: `The sun was hot and the queue was long. By the time Otto reached the front, the ice cream was already dripping down the side of the cone. He licked all the way round to catch it. His hand still ended up sticky.`,
    questions: [
      {
        id: 'q1',
        prompt: 'Why was the ice cream dripping?',
        answer: 'The sun was hot',
        distractors: ['It was old', 'He shook it', 'The cone was broken'],
        explanation: 'The first sentence says the sun was hot, which melts ice cream.',
        skill: 'inference',
      },
      {
        id: 'q2',
        prompt: 'What did Otto do to stop the drips?',
        answer: 'Licked round the cone',
        distractors: ['Used a spoon', 'Threw it away', 'Put it in the shade'],
        explanation: 'He licked all the way round to catch it.',
        skill: 'detail',
      },
      {
        id: 'q3',
        prompt: 'Did Otto stay clean?',
        answer: 'No, his hand was sticky',
        distractors: ['Yes, completely', 'He did not eat it', 'The story does not say'],
        explanation: 'The last sentence says his hand still ended up sticky.',
        skill: 'detail',
      },
    ],
  },
  {
    title: 'The Cat in the Window',
    icon: '🐈',
    text: `There is a grey cat in the window of the corner house. It sits in the same square of sun every morning. When clouds come, the cat moves to the back of the sill. Nobody has ever seen it outside.`,
    questions: [
      {
        id: 'q1',
        prompt: 'Why does the cat sit in that spot?',
        answer: 'It is warm in the sun',
        distractors: ['It is hungry', 'It wants to escape', 'It can see the road'],
        explanation: 'It sits in the square of sun and moves when clouds come, so it wants the warmth.',
        skill: 'inference',
      },
      {
        id: 'q2',
        prompt: 'What colour is the cat?',
        answer: 'Grey',
        distractors: ['Black', 'Ginger', 'White'],
        explanation: 'The first sentence says there is a grey cat in the window.',
        skill: 'detail',
      },
      {
        id: 'q3',
        prompt: 'When does the cat move to the back of the sill?',
        answer: 'When clouds come',
        distractors: ['At night', 'When it rains', 'When someone knocks'],
        explanation: 'The story says when clouds come, the cat moves to the back of the sill.',
        skill: 'detail',
      },
    ],
  },
  {
    title: 'Muddy Boots',
    icon: '🥾',
    text: `It had rained for three days. Priya walked the long way home across the field. Her boots grew heavier with every step. At the door her mum pointed at the mat without saying a word. Priya left the boots outside.`,
    questions: [
      {
        id: 'q1',
        prompt: 'Why did the boots grow heavier?',
        answer: 'Mud stuck to them',
        distractors: ['They filled with rain', 'They were too big', 'She was tired'],
        explanation: 'She crossed a field after three days of rain, so mud built up on her boots.',
        skill: 'inference',
      },
      {
        id: 'q2',
        prompt: 'What did her mum do at the door?',
        answer: 'Pointed at the mat',
        distractors: ['Shouted', 'Fetched a towel', 'Opened the window'],
        explanation: 'Her mum pointed at the mat without saying a word.',
        skill: 'detail',
      },
      {
        id: 'q3',
        prompt: 'Why did her mum say nothing?',
        answer: 'Priya already knew the rule',
        distractors: ['She was asleep', 'She was angry', 'She could not speak'],
        explanation: 'One point at the mat was enough, so this had clearly happened before.',
        skill: 'inference',
      },
    ],
  },
  {
    title: 'The Card That Was Late',
    icon: '💌',
    text: `Ellis made a birthday card for his cousin but forgot to post it. He found it in his bag a week later. He added a new line at the bottom that said sorry it is late. His cousin said it was the best card.`,
    questions: [
      {
        id: 'q1',
        prompt: 'Why was the card late?',
        answer: 'Ellis forgot to post it',
        distractors: ['The post was slow', 'He lost the address', 'He made it twice'],
        explanation: 'The story says he made it but forgot to post it, then found it a week later.',
        skill: 'detail',
      },
      {
        id: 'q2',
        prompt: 'What did Ellis add to the card?',
        answer: 'A line saying sorry it is late',
        distractors: ['A stamp', 'A drawing', 'A photograph'],
        explanation: 'He added a new line at the bottom that said sorry it is late.',
        skill: 'detail',
      },
      {
        id: 'q3',
        prompt: 'How did his cousin feel about it?',
        answer: 'She liked it very much',
        distractors: ['She was cross', 'She never opened it', 'She sent it back'],
        explanation: 'His cousin said it was the best card.',
        skill: 'inference',
      },
    ],
  },
  {
    title: 'Worms After Rain',
    icon: '🪱',
    text: `After heavy rain the worms come up onto the path. Jonah counted eleven on the way to school. He moved four of them back onto the grass so they would not be stepped on. His shoes got wet but he did not mind.`,
    questions: [
      {
        id: 'q1',
        prompt: 'How many worms did Jonah count?',
        answer: 'Eleven',
        distractors: ['Four', 'Seven', 'Twenty'],
        explanation: 'The story says he counted eleven on the way to school.',
        skill: 'detail',
      },
      {
        id: 'q2',
        prompt: 'Why did Jonah move some worms?',
        answer: 'So they would not be stepped on',
        distractors: ['To take them home', 'To count them', 'To feed the birds'],
        explanation: 'He moved four onto the grass so they would not be stepped on.',
        skill: 'detail',
      },
      {
        id: 'q3',
        prompt: 'What kind of person is Jonah?',
        answer: 'Kind to animals',
        distractors: ['Afraid of worms', 'Always late', 'Untidy'],
        explanation: 'He stopped to move worms to safety and did not mind wet shoes.',
        skill: 'inference',
      },
    ],
  },
  {
    title: 'The Squeaky Gate',
    icon: '🚪',
    text: `The garden gate squealed whenever anyone opened it. Nobody could sneak in or out. Gran said it was better than a doorbell. Then Uncle Ray oiled the hinge. That night the cat got in and ate the butter.`,
    questions: [
      {
        id: 'q1',
        prompt: 'Why did Gran like the squeak?',
        answer: 'It told her someone was coming',
        distractors: ['She liked the sound', 'It kept the cat warm', 'It scared birds away'],
        explanation: 'She said it was better than a doorbell, so it warned her of visitors.',
        skill: 'inference',
      },
      {
        id: 'q2',
        prompt: 'What did Uncle Ray do?',
        answer: 'He oiled the hinge',
        distractors: ['He painted the gate', 'He locked it', 'He took it off'],
        explanation: 'The story says Uncle Ray oiled the hinge.',
        skill: 'detail',
      },
      {
        id: 'q3',
        prompt: 'Why could the cat get in unnoticed?',
        answer: 'The gate no longer squeaked',
        distractors: ['The gate was left open', 'It was dark', 'Gran was out'],
        explanation: 'Once the hinge was oiled there was no warning noise.',
        skill: 'inference',
      },
    ],
  },
  {
    title: 'The Shopping List',
    icon: '🛒',
    text: `Mum wrote six things on a list and gave it to Nadia. Nadia found five of them easily. The last one was baking soda and she did not know what it looked like. She asked a woman in a green apron, who walked her to the right shelf.`,
    questions: [
      {
        id: 'q1',
        prompt: 'How many things were on the list?',
        answer: 'Six',
        distractors: ['Five', 'Three', 'Ten'],
        explanation: 'The story says Mum wrote six things on a list.',
        skill: 'detail',
      },
      {
        id: 'q2',
        prompt: 'What did Nadia do when she was stuck?',
        answer: 'She asked for help',
        distractors: ['She went home', 'She guessed', 'She bought nothing'],
        explanation: 'She asked a woman in a green apron, who showed her the shelf.',
        skill: 'inference',
      },
      {
        id: 'q3',
        prompt: 'Who was the woman in the green apron?',
        answer: 'Someone who worked in the shop',
        distractors: ['Nadia\'s mum', 'Another shopper', 'A teacher'],
        explanation: 'She wore an apron and knew where things were, so she worked there.',
        skill: 'inference',
      },
    ],
  },
  {
    title: 'Washing on the Line',
    icon: '🧺',
    text: `Gran hung the washing out on a cold bright morning. By lunchtime the shirts were stiff as boards. She carried them inside and stood them against the wall. As they warmed, they went soft and flopped over one by one.`,
    questions: [
      {
        id: 'q1',
        prompt: 'Why were the shirts stiff?',
        answer: 'They had frozen',
        distractors: ['They were starched', 'They were still wet', 'They were new'],
        explanation: 'It was a cold morning, and the shirts went soft once they warmed indoors.',
        skill: 'inference',
      },
      {
        id: 'q2',
        prompt: 'What are the shirts compared to?',
        answer: 'Boards',
        distractors: ['Flags', 'Sails', 'Paper'],
        explanation: 'The story says the shirts were stiff as boards.',
        skill: 'vocabulary',
      },
      {
        id: 'q3',
        prompt: 'What happened last?',
        answer: 'The shirts flopped over',
        distractors: ['Gran hung them out', 'They froze', 'Gran carried them in'],
        explanation: 'As they warmed, they went soft and flopped over one by one.',
        skill: 'sequence',
      },
    ],
  },
  {
    title: 'The Broken Crayon',
    icon: '🖍️',
    text: `Iris pressed too hard and her best blue crayon snapped in half. She was upset until she noticed something. Now she had two crayons that both worked. She used one for the sky and one for the sea in the same picture.`,
    questions: [
      {
        id: 'q1',
        prompt: 'How did the crayon break?',
        answer: 'Iris pressed too hard',
        distractors: ['She dropped it', 'Someone sat on it', 'It was already cracked'],
        explanation: 'The first sentence says she pressed too hard and it snapped in half.',
        skill: 'detail',
      },
      {
        id: 'q2',
        prompt: 'Why did Iris stop being upset?',
        answer: 'She had two working crayons',
        distractors: ['She got a new one', 'She stopped drawing', 'Her mum mended it'],
        explanation: 'She noticed that now she had two crayons that both worked.',
        skill: 'inference',
      },
      {
        id: 'q3',
        prompt: 'What is this story mostly about?',
        answer: 'Finding the good side of a problem',
        distractors: ['How to draw the sea', 'Looking after crayons', 'Sharing with a friend'],
        explanation: 'A broken crayon turns into two useful ones, which is the whole point.',
        skill: 'mainIdea',
      },
    ],
  },
  {
    title: 'Shadow Games',
    icon: '🌞',
    text: `In the early morning Leo\'s shadow was long enough to reach the fence. At noon it was a short dark puddle under his shoes. By teatime it stretched out again the other way. He drew round it three times with chalk.`,
    questions: [
      {
        id: 'q1',
        prompt: 'When was the shadow shortest?',
        answer: 'At noon',
        distractors: ['In the early morning', 'At teatime', 'At night'],
        explanation: 'At noon it was a short dark puddle under his shoes.',
        skill: 'detail',
      },
      {
        id: 'q2',
        prompt: 'What made the shadow change?',
        answer: 'The sun moved across the sky',
        distractors: ['Leo grew', 'The fence moved', 'The chalk faded'],
        explanation: 'The shadow changed length and direction through the day as the sun moved.',
        skill: 'inference',
      },
      {
        id: 'q3',
        prompt: 'How many times did Leo draw round his shadow?',
        answer: 'Three',
        distractors: ['Once', 'Twice', 'Five times'],
        explanation: 'The last sentence says he drew round it three times with chalk.',
        skill: 'detail',
      },
    ],
  },
  {
    title: 'A Hole in the Sock',
    icon: '🧦',
    text: `Toby\'s big toe poked through his sock. He hid it under the table at dinner. Later his gran took out a needle and a small wooden egg. She slid the egg inside the sock and sewed the hole shut. It felt lumpy but warm.`,
    questions: [
      {
        id: 'q1',
        prompt: 'Why did Toby hide his foot?',
        answer: 'He was embarrassed about the hole',
        distractors: ['His foot was cold', 'He had hurt his toe', 'The floor was wet'],
        explanation: 'His toe poked through and he hid it under the table, so he felt embarrassed.',
        skill: 'inference',
      },
      {
        id: 'q2',
        prompt: 'What did Gran put inside the sock?',
        answer: 'A wooden egg',
        distractors: ['A stone', 'A ball of wool', 'Her hand'],
        explanation: 'She slid a small wooden egg inside the sock before sewing.',
        skill: 'detail',
      },
      {
        id: 'q3',
        prompt: 'Why would the egg help?',
        answer: 'It held the sock in shape to sew',
        distractors: ['It made it warmer', 'It weighed it down', 'It smelled nice'],
        explanation: 'A firm shape inside the sock lets the needle work on a flat surface.',
        skill: 'inference',
      },
    ],
  },
  {
    title: 'The First Snow',
    icon: '❄️',
    text: `The first flakes came down while the class was doing sums. One by one the children stopped writing and looked at the window. Miss Yates put down her pen too. Nobody said anything for a long moment. Then everyone spoke at once.`,
    questions: [
      {
        id: 'q1',
        prompt: 'What were the children doing when the snow began?',
        answer: 'Sums',
        distractors: ['Reading', 'Painting', 'Singing'],
        explanation: 'The first flakes came down while the class was doing sums.',
        skill: 'detail',
      },
      {
        id: 'q2',
        prompt: 'What did Miss Yates do?',
        answer: 'She put down her pen and looked too',
        distractors: ['She closed the blinds', 'She carried on teaching', 'She sent them outside'],
        explanation: 'The story says Miss Yates put down her pen too.',
        skill: 'detail',
      },
      {
        id: 'q3',
        prompt: 'Why did nobody speak at first?',
        answer: 'They were all watching the snow',
        distractors: ['They were in trouble', 'They were asleep', 'The room was empty'],
        explanation: 'Everyone had stopped to look, and the talking burst out afterwards.',
        skill: 'inference',
      },
    ],
  },
  {
    title: 'The Runaway Hat',
    icon: '🎩',
    text: `A gust took Grandad\'s hat off his head at the seafront. It rolled along the path on its brim like a wheel. Three people tried to stand on it and missed. A small dog finally caught it and would not let go.`,
    questions: [
      {
        id: 'q1',
        prompt: 'What is the hat compared to?',
        answer: 'A wheel',
        distractors: ['A bird', 'A boat', 'A ball'],
        explanation: 'It rolled along on its brim like a wheel.',
        skill: 'vocabulary',
      },
      {
        id: 'q2',
        prompt: 'How many people tried to stop it?',
        answer: 'Three',
        distractors: ['One', 'Two', 'Nobody'],
        explanation: 'The story says three people tried to stand on it and missed.',
        skill: 'detail',
      },
      {
        id: 'q3',
        prompt: 'Who caught the hat in the end?',
        answer: 'A small dog',
        distractors: ['Grandad', 'A passer-by', 'Nobody'],
        explanation: 'A small dog finally caught it and would not let go.',
        skill: 'sequence',
      },
    ],
  },
  {
    title: 'Feeding the Fish',
    icon: '🐟',
    text: `Ren was told to give the fish one pinch of food each day. He thought more food would make them happy, so he gave three. The water went cloudy by Friday. His dad showed him how the extra food had simply sunk and spoiled.`,
    questions: [
      {
        id: 'q1',
        prompt: 'How much food should Ren have given?',
        answer: 'One pinch a day',
        distractors: ['Three pinches a day', 'As much as they wanted', 'One pinch a week'],
        explanation: 'He was told to give one pinch each day.',
        skill: 'detail',
      },
      {
        id: 'q2',
        prompt: 'Why did the water go cloudy?',
        answer: 'Uneaten food spoiled in it',
        distractors: ['The fish were ill', 'The tank leaked', 'The light was off'],
        explanation: 'His dad showed him the extra food had sunk and spoiled.',
        skill: 'inference',
      },
      {
        id: 'q3',
        prompt: 'What is this story mostly about?',
        answer: 'More is not always better',
        distractors: ['How to clean a tank', 'Choosing a pet', 'Fish are hard to keep'],
        explanation: 'Ren meant well by giving extra food, and that is exactly what caused the problem.',
        skill: 'mainIdea',
      },
    ],
  },
  {
    title: 'The Long Queue',
    icon: '🎡',
    text: `The queue for the big wheel went twice round the railing. Marta counted forty people ahead of her. She read her comic while she waited. When her turn came the sun was going down, and from the top she could see the whole town lit up.`,
    questions: [
      {
        id: 'q1',
        prompt: 'How many people were ahead of Marta?',
        answer: 'Forty',
        distractors: ['Fourteen', 'Four', 'A hundred'],
        explanation: 'The story says Marta counted forty people ahead of her.',
        skill: 'detail',
      },
      {
        id: 'q2',
        prompt: 'What did Marta do while waiting?',
        answer: 'Read her comic',
        distractors: ['Slept', 'Ate an ice cream', 'Talked to a friend'],
        explanation: 'She read her comic while she waited.',
        skill: 'detail',
      },
      {
        id: 'q3',
        prompt: 'Was the long wait worth it?',
        answer: 'Yes, she saw the town lit up',
        distractors: ['No, she missed her turn', 'No, it was dark', 'The story does not say'],
        explanation: 'From the top she could see the whole town lit up, which only happened because she waited.',
        skill: 'inference',
      },
    ],
  },
  {
    title: 'The Quiet Corner',
    icon: '🛋️',
    text: `There is a corner of the classroom with a rug and two cushions. Anyone can go there when the room feels too loud. You do not have to say why. Most days it is empty. On Monday afternoons there is often a queue.`,
    questions: [
      {
        id: 'q1',
        prompt: 'What is the corner for?',
        answer: 'Getting away from noise',
        distractors: ['Reading aloud', 'Punishment', 'Group work'],
        explanation: 'Anyone can go there when the room feels too loud.',
        skill: 'detail',
      },
      {
        id: 'q2',
        prompt: 'Do you have to explain why you go?',
        answer: 'No',
        distractors: ['Yes, to the teacher', 'Yes, in writing', 'Only on Mondays'],
        explanation: 'The story says you do not have to say why.',
        skill: 'detail',
      },
      {
        id: 'q3',
        prompt: 'What does the Monday queue suggest?',
        answer: 'Mondays feel harder for many children',
        distractors: ['The rug is new', 'Mondays are quiet', 'Only one child uses it'],
        explanation: 'Most days it is empty, but on Monday afternoons several children want it.',
        skill: 'inference',
      },
    ],
  },
  {
    title: 'Lost at the Market',
    icon: '🍎',
    text: `For one long minute Amara could not see her dad anywhere. She remembered the rule and stayed exactly where she was. She counted the apples on the nearest stall to keep calm. At twenty-six a hand landed on her shoulder. It was him.`,
    questions: [
      {
        id: 'q1',
        prompt: 'What did Amara do when she could not see her dad?',
        answer: 'Stayed where she was',
        distractors: ['Ran to look for him', 'Left the market', 'Shouted for the police'],
        explanation: 'She remembered the rule and stayed exactly where she was.',
        skill: 'detail',
      },
      {
        id: 'q2',
        prompt: 'Why did she count apples?',
        answer: 'To keep herself calm',
        distractors: ['To buy them', 'To pass a test', 'To find her dad'],
        explanation: 'The story says she counted the apples to keep calm.',
        skill: 'inference',
      },
      {
        id: 'q3',
        prompt: 'How long was she alone?',
        answer: 'About a minute',
        distractors: ['An hour', 'All afternoon', 'Twenty-six minutes'],
        explanation: 'The first sentence says it was one long minute.',
        skill: 'detail',
      },
    ],
  },
  {
    title: 'The Spider in the Bath',
    icon: '🕷️',
    text: `There was a spider in the bath again. Dad fetched a glass and a piece of card. He put the glass over the spider and slid the card underneath. Then he carried the whole thing to the window. The spider walked off into the ivy.`,
    questions: [
      {
        id: 'q1',
        prompt: 'What did Dad use to catch the spider?',
        answer: 'A glass and a card',
        distractors: ['A cup and a spoon', 'His hands', 'A jar and a lid'],
        explanation: 'He fetched a glass and a piece of card, then slid the card underneath.',
        skill: 'detail',
      },
      {
        id: 'q2',
        prompt: 'Why did he use a card?',
        answer: 'To close the glass and carry it',
        distractors: ['To scare the spider', 'To clean the bath', 'To squash it'],
        explanation: 'The card sealed the glass so the spider could be carried without escaping.',
        skill: 'inference',
      },
      {
        id: 'q3',
        prompt: 'What happened to the spider?',
        answer: 'It was let go outside',
        distractors: ['It was killed', 'It stayed in the bath', 'It hid in the card'],
        explanation: 'It walked off into the ivy after Dad carried it to the window.',
        skill: 'sequence',
      },
    ],
  },
  {
    title: 'A New Word',
    icon: '💬',
    text: `Yusuf heard his teacher say the word enormous. He liked the sound of it. All week he used it whenever he could. The dog was enormous. His sandwich was enormous. By Friday even his little sister was saying it.`,
    questions: [
      {
        id: 'q1',
        prompt: 'What does "enormous" mean?',
        answer: 'Very big',
        distractors: ['Very fast', 'Very loud', 'Very old'],
        explanation: 'Yusuf uses it for a dog and a sandwich he thinks are large.',
        skill: 'vocabulary',
      },
      {
        id: 'q2',
        prompt: 'Where did Yusuf hear the word?',
        answer: 'From his teacher',
        distractors: ['On television', 'From his sister', 'In a book'],
        explanation: 'The first sentence says he heard his teacher say it.',
        skill: 'detail',
      },
      {
        id: 'q3',
        prompt: 'Why was his sister saying it by Friday?',
        answer: 'She copied Yusuf',
        distractors: ['She learned it at school', 'She read it', 'She made it up'],
        explanation: 'He used it all week at home, so she picked it up from him.',
        skill: 'inference',
      },
    ],
  },
  {
    title: 'Marks on the Door',
    icon: '📏',
    text: `There is a line of pencil marks on the kitchen door frame. Each one has a name and a date beside it. The lowest mark is Dad, aged four. The highest is Cousin Ellie, who is nearly grown. Every birthday another line is added.`,
    questions: [
      {
        id: 'q1',
        prompt: 'What do the marks show?',
        answer: 'How tall people were',
        distractors: ['Where to hang coats', 'How old the house is', 'Who lives there'],
        explanation: 'Each mark has a name and date, and the highest belongs to the oldest child.',
        skill: 'inference',
      },
      {
        id: 'q2',
        prompt: 'Whose mark is lowest?',
        answer: 'Dad\'s, when he was four',
        distractors: ['Cousin Ellie\'s', 'The baby\'s', 'Nobody knows'],
        explanation: 'The story says the lowest mark is Dad, aged four.',
        skill: 'detail',
      },
      {
        id: 'q3',
        prompt: 'When is a new line added?',
        answer: 'Every birthday',
        distractors: ['Every Monday', 'Every summer', 'When someone moves in'],
        explanation: 'The last sentence says every birthday another line is added.',
        skill: 'detail',
      },
    ],
  },
  {
    title: 'Popcorn',
    icon: '🍿',
    text: `The pan went on the heat with a lid pressed down tight. For a long time nothing happened at all. Then one kernel popped, then five, then too many to count. Mira held the lid on while the pan rattled under her hands.`,
    questions: [
      {
        id: 'q1',
        prompt: 'Why did Mira hold the lid down?',
        answer: 'To keep the popcorn inside',
        distractors: ['To keep it warm', 'To stop the smell', 'To cook it faster'],
        explanation: 'The pan rattled as the corn popped, so the lid kept it from flying out.',
        skill: 'inference',
      },
      {
        id: 'q2',
        prompt: 'What happened first?',
        answer: 'Nothing happened for a while',
        distractors: ['One kernel popped', 'The pan rattled', 'Five popped at once'],
        explanation: 'For a long time nothing happened at all, before the first pop.',
        skill: 'sequence',
      },
      {
        id: 'q3',
        prompt: 'What does "kernel" mean here?',
        answer: 'A single seed of corn',
        distractors: ['A saucepan', 'A handful', 'A kind of heat'],
        explanation: 'One kernel popped, then five, so a kernel is one piece of corn.',
        skill: 'vocabulary',
      },
    ],
  },
  {
    title: 'The Key Under the Pot',
    icon: '🔑',
    text: `The spare key lives under the third flowerpot by the step. Only the family knows which pot. Once, Aunt Jo forgot and lifted all seven. She found a beetle, two woodlice and a very old marble before she found the key.`,
    questions: [
      {
        id: 'q1',
        prompt: 'Which pot hides the key?',
        answer: 'The third one',
        distractors: ['The first one', 'The last one', 'The biggest one'],
        explanation: 'The story says the spare key lives under the third flowerpot.',
        skill: 'detail',
      },
      {
        id: 'q2',
        prompt: 'Why did Aunt Jo lift all seven pots?',
        answer: 'She had forgotten which one',
        distractors: ['She was cleaning', 'She wanted the marble', 'She was looking for beetles'],
        explanation: 'The story says Aunt Jo forgot and so lifted all seven.',
        skill: 'inference',
      },
      {
        id: 'q3',
        prompt: 'What did she find besides the key?',
        answer: 'A beetle, woodlice and a marble',
        distractors: ['A coin and a button', 'Nothing at all', 'Another key'],
        explanation: 'She found a beetle, two woodlice and a very old marble.',
        skill: 'detail',
      },
    ],
  },
  {
    title: 'Sandcastle and Sea',
    icon: '🏖️',
    text: `Callum built his castle close to the water so he could fill the moat. The first wave filled it beautifully. The fourth wave took away a tower. By the time the tide came fully in there was only a smooth wet patch left.`,
    questions: [
      {
        id: 'q1',
        prompt: 'Why did Callum build near the water?',
        answer: 'So he could fill the moat',
        distractors: ['The sand was softer', 'It was shady', 'His friends were there'],
        explanation: 'The first sentence says he built close to the water so he could fill the moat.',
        skill: 'detail',
      },
      {
        id: 'q2',
        prompt: 'What was the problem with that spot?',
        answer: 'The rising tide washed it away',
        distractors: ['The sand was too dry', 'People walked on it', 'It was too windy'],
        explanation: 'Waves took a tower and the tide eventually left only a smooth patch.',
        skill: 'inference',
      },
      {
        id: 'q3',
        prompt: 'What happened last?',
        answer: 'Only a wet patch was left',
        distractors: ['The moat filled', 'A tower fell', 'Callum built the castle'],
        explanation: 'By the time the tide came fully in there was only a smooth wet patch.',
        skill: 'sequence',
      },
    ],
  },
  {
    title: 'The Torch Under the Blanket',
    icon: '🔦',
    text: `Noor was supposed to be asleep. Instead she read under the blanket with a torch. The light glowed through the cloth like a small moon. Her mum saw it from the doorway and said nothing, but the batteries were gone by morning.`,
    questions: [
      {
        id: 'q1',
        prompt: 'What was Noor doing?',
        answer: 'Reading after bedtime',
        distractors: ['Hiding from the dark', 'Looking for something', 'Playing a game'],
        explanation: 'She was supposed to be asleep but read under the blanket with a torch.',
        skill: 'detail',
      },
      {
        id: 'q2',
        prompt: 'What is the glow compared to?',
        answer: 'A small moon',
        distractors: ['A candle', 'A star', 'A lamp'],
        explanation: 'The light glowed through the cloth like a small moon.',
        skill: 'vocabulary',
      },
      {
        id: 'q3',
        prompt: 'Why were the batteries gone by morning?',
        answer: 'Her mum took them out',
        distractors: ['They fell out', 'Noor lost them', 'They were never there'],
        explanation: 'Her mum saw the light and said nothing, but acted quietly instead.',
        skill: 'inference',
      },
    ],
  },
  {
    title: 'Taking Turns',
    icon: '🛴',
    text: `There was one scooter and two children. Ravi said he would count to fifty and then swap. He counted fast at first, then slower and slower near the end. His friend noticed but decided not to argue. The next turn lasted much longer.`,
    questions: [
      {
        id: 'q1',
        prompt: 'How were the children sharing?',
        answer: 'Counting to fifty then swapping',
        distractors: ['Taking a day each', 'Using a timer', 'Riding together'],
        explanation: 'Ravi said he would count to fifty and then swap.',
        skill: 'detail',
      },
      {
        id: 'q2',
        prompt: 'Why did Ravi slow his counting?',
        answer: 'To make his own turn longer',
        distractors: ['He was tired', 'He lost his place', 'He was being fair'],
        explanation: 'Counting slower near the end stretches out the turn he was on.',
        skill: 'inference',
      },
      {
        id: 'q3',
        prompt: 'What does the last sentence suggest?',
        answer: 'His friend did the same thing back',
        distractors: ['They stopped playing', 'Ravi apologised', 'The scooter broke'],
        explanation: 'The next turn lasted much longer, so his friend counted slowly too.',
        skill: 'inference',
      },
    ],
  },
  {
    title: 'The Cactus',
    icon: '🌵',
    text: `Aunt Beth gave Sofia a cactus in a clay pot. She said to water it once a month and no more. Sofia thought that sounded mean and watered it every week. The cactus went soft and brown. Plants from the desert do not want much.`,
    questions: [
      {
        id: 'q1',
        prompt: 'How often should the cactus be watered?',
        answer: 'Once a month',
        distractors: ['Once a week', 'Every day', 'Never'],
        explanation: 'Aunt Beth said to water it once a month and no more.',
        skill: 'detail',
      },
      {
        id: 'q2',
        prompt: 'Why did the cactus go soft and brown?',
        answer: 'It had too much water',
        distractors: ['It was too cold', 'It had no light', 'The pot was small'],
        explanation: 'Sofia watered it every week, far more than a desert plant needs.',
        skill: 'inference',
      },
      {
        id: 'q3',
        prompt: 'What is this story mostly about?',
        answer: 'Caring for something the way it needs',
        distractors: ['Choosing a pot', 'Deserts are hot', 'Aunts give odd presents'],
        explanation: 'Sofia was kind but did the wrong thing, because a cactus needs very little.',
        skill: 'mainIdea',
      },
    ],
  },
  {
    title: 'The Bird That Copied',
    icon: '🦜',
    text: `Next door there is a bird that copies sounds. It does the phone, the microwave and the neighbour\'s cough. Last week it learned the ice cream van. Half the street went outside with their coins ready. There was no van.`,
    questions: [
      {
        id: 'q1',
        prompt: 'What can the bird do?',
        answer: 'Copy sounds it hears',
        distractors: ['Sing songs', 'Say its own name', 'Open the window'],
        explanation: 'It copies the phone, the microwave and a cough.',
        skill: 'detail',
      },
      {
        id: 'q2',
        prompt: 'Why did people go outside with coins?',
        answer: 'They thought the ice cream van had come',
        distractors: ['To feed the bird', 'To pay the neighbour', 'To catch a bus'],
        explanation: 'The bird had learned the ice cream van sound, and they believed it.',
        skill: 'inference',
      },
      {
        id: 'q3',
        prompt: 'Was there really a van?',
        answer: 'No',
        distractors: ['Yes', 'It came later', 'The story does not say'],
        explanation: 'The last sentence says there was no van.',
        skill: 'detail',
      },
    ],
  },
  {
    title: 'Floating',
    icon: '🏊',
    text: `Ines was afraid to put her face in the water. Her teacher told her to lie back and look straight up at the ceiling. She held Ines under the shoulders and then quietly let go. Ines floated on her own for six whole seconds.`,
    questions: [
      {
        id: 'q1',
        prompt: 'What was Ines afraid of?',
        answer: 'Putting her face in the water',
        distractors: ['Deep water', 'The teacher', 'Swimming fast'],
        explanation: 'The first sentence says she was afraid to put her face in the water.',
        skill: 'detail',
      },
      {
        id: 'q2',
        prompt: 'Why did the teacher let go quietly?',
        answer: 'So Ines would not panic',
        distractors: ['She was tired', 'She was called away', 'To make Ines swim'],
        explanation: 'Letting go without announcing it kept Ines calm enough to float.',
        skill: 'inference',
      },
      {
        id: 'q3',
        prompt: 'How long did Ines float alone?',
        answer: 'Six seconds',
        distractors: ['Six minutes', 'Two seconds', 'A whole lap'],
        explanation: 'The last sentence says she floated on her own for six whole seconds.',
        skill: 'detail',
      },
    ],
  },
  {
    title: 'The Wasp and the Jam',
    icon: '🐝',
    text: `A wasp found the jam at the picnic. Everyone waved their arms and shouted. The wasp only got crosser. Then Grandpa put a spoonful of jam on a plate at the far end of the table. The wasp went to the plate and stayed there.`,
    questions: [
      {
        id: 'q1',
        prompt: 'What did Grandpa do?',
        answer: 'Put jam on a plate further away',
        distractors: ['Swatted the wasp', 'Covered the jam', 'Moved everyone indoors'],
        explanation: 'He put a spoonful of jam on a plate at the far end of the table.',
        skill: 'detail',
      },
      {
        id: 'q2',
        prompt: 'Why did waving not work?',
        answer: 'It made the wasp crosser',
        distractors: ['It was too slow', 'The wasp could not see', 'It blew the jam away'],
        explanation: 'The story says the wasp only got crosser.',
        skill: 'detail',
      },
      {
        id: 'q3',
        prompt: 'Why did Grandpa\'s idea work?',
        answer: 'The wasp wanted jam, not people',
        distractors: ['The plate was shiny', 'The wasp was full', 'It was colder there'],
        explanation: 'Given jam of its own, the wasp had no reason to bother anyone.',
        skill: 'inference',
      },
    ],
  },
  {
    title: 'Down the Back of the Sofa',
    icon: '🛋️',
    text: `Dad tipped the old sofa forward to move it. Coins rained onto the carpet. There were also three pens, a hair clip and a library card from four years ago. The coins came to two pounds and sixty pence. Dad said finders keepers.`,
    questions: [
      {
        id: 'q1',
        prompt: 'What fell out of the sofa first?',
        answer: 'Coins',
        distractors: ['Pens', 'A hair clip', 'A library card'],
        explanation: 'When Dad tipped it forward, coins rained onto the carpet.',
        skill: 'sequence',
      },
      {
        id: 'q2',
        prompt: 'How much money was there?',
        answer: 'Two pounds sixty',
        distractors: ['Two pounds sixteen', 'Sixty pence', 'Four pounds'],
        explanation: 'The coins came to two pounds and sixty pence.',
        skill: 'detail',
      },
      {
        id: 'q3',
        prompt: 'How old was the library card?',
        answer: 'Four years old',
        distractors: ['A month old', 'Brand new', 'Ten years old'],
        explanation: 'The story says a library card from four years ago.',
        skill: 'detail',
      },
    ],
  },
  {
    title: 'The Photograph',
    icon: '🖼️',
    text: `In the hall there is a photograph of a young woman on a bicycle. She is laughing at something outside the picture. It is Great-Gran, aged nineteen. Nobody now alive knows what she was laughing at. That is the best part.`,
    questions: [
      {
        id: 'q1',
        prompt: 'Who is in the photograph?',
        answer: 'Great-Gran when she was young',
        distractors: ['The narrator', 'A stranger', 'Great-Gran now'],
        explanation: 'The story says it is Great-Gran, aged nineteen.',
        skill: 'detail',
      },
      {
        id: 'q2',
        prompt: 'Why does nobody know what she was laughing at?',
        answer: 'It happened outside the picture long ago',
        distractors: ['The photo is torn', 'She never said', 'It is too dark'],
        explanation: 'She is laughing at something outside the picture, and nobody alive remembers.',
        skill: 'inference',
      },
      {
        id: 'q3',
        prompt: 'How does the writer feel about the mystery?',
        answer: 'They like it',
        distractors: ['It annoys them', 'It frightens them', 'They want it solved'],
        explanation: 'The last line says that is the best part.',
        skill: 'inference',
      },
    ],
  },
  {
    title: 'The Trainers That Light Up',
    icon: '✨',
    text: `Dev\'s new trainers flash red when he stamps. He stamped all the way down the corridor on the first morning. By the second day the lights annoyed everyone, including Dev. Now he saves the stamping for the walk home.`,
    questions: [
      {
        id: 'q1',
        prompt: 'What makes the trainers flash?',
        answer: 'Stamping',
        distractors: ['A switch', 'Sunlight', 'Running fast'],
        explanation: 'The story says they flash red when he stamps.',
        skill: 'detail',
      },
      {
        id: 'q2',
        prompt: 'Why does Dev only stamp on the way home now?',
        answer: 'The lights annoyed people indoors',
        distractors: ['The lights broke', 'He grew out of them', 'It is a school rule'],
        explanation: 'By the second day the lights annoyed everyone, including Dev.',
        skill: 'inference',
      },
      {
        id: 'q3',
        prompt: 'Who else got tired of the flashing?',
        answer: 'Dev himself',
        distractors: ['Only the teacher', 'Nobody', 'His parents'],
        explanation: 'The story says the lights annoyed everyone, including Dev.',
        skill: 'detail',
      },
    ],
  },
  {
    title: 'The Slowest Reader',
    icon: '📖',
    text: `Bea reads more slowly than anyone in her group. She stops at words she likes and says them again. She always knows what happened and why. Her teacher says there is no prize for finishing first. Bea has read the same book four times.`,
    questions: [
      {
        id: 'q1',
        prompt: 'Why does Bea stop while reading?',
        answer: 'To say words she likes again',
        distractors: ['She loses her place', 'She cannot read them', 'She gets tired'],
        explanation: 'The story says she stops at words she likes and says them again.',
        skill: 'detail',
      },
      {
        id: 'q2',
        prompt: 'Is reading slowly a problem for Bea?',
        answer: 'No, she understands everything',
        distractors: ['Yes, she misses the ending', 'Yes, she never finishes', 'The story does not say'],
        explanation: 'She always knows what happened and why, and her teacher is not worried.',
        skill: 'inference',
      },
      {
        id: 'q3',
        prompt: 'What is this story mostly about?',
        answer: 'Reading well matters more than reading fast',
        distractors: ['Choosing a good book', 'A reading competition', 'How to read aloud'],
        explanation: 'There is no prize for finishing first, and Bea understands what she reads.',
        skill: 'mainIdea',
      },
    ],
  },
  {
    title: 'Feathers in the Yard',
    icon: '🪶',
    text: `One morning the yard was covered in small grey feathers. There was no bird and no blood. Mum said a cat had probably had a fright and dropped its catch. The feathers blew about for two days and then were gone.`,
    questions: [
      {
        id: 'q1',
        prompt: 'What was in the yard?',
        answer: 'Small grey feathers',
        distractors: ['A grey bird', 'A cat', 'Broken eggs'],
        explanation: 'The first sentence says the yard was covered in small grey feathers.',
        skill: 'detail',
      },
      {
        id: 'q2',
        prompt: 'What did Mum think had happened?',
        answer: 'A cat dropped a bird it had caught',
        distractors: ['A bird moulted', 'A pillow burst', 'Someone emptied a bag'],
        explanation: 'Mum said a cat had probably had a fright and dropped its catch.',
        skill: 'detail',
      },
      {
        id: 'q3',
        prompt: 'Why is Mum not certain?',
        answer: 'Nobody saw it happen',
        distractors: ['She was away', 'She cannot see well', 'She does not like cats'],
        explanation: 'She says "probably" because there was no bird and no witness.',
        skill: 'inference',
      },
    ],
  },
  {
    title: 'The Last Day of Term',
    icon: '🎒',
    text: `On the last day the walls came bare. All the paintings went home in rolls under arms. The room looked bigger and somehow sadder. Miss Owen said it would be full of somebody else\'s work in September. Then she let them out early.`,
    questions: [
      {
        id: 'q1',
        prompt: 'Why did the walls look bare?',
        answer: 'The children took their work home',
        distractors: ['They were painted', 'The paintings fell', 'There had been none'],
        explanation: 'All the paintings went home in rolls under arms.',
        skill: 'inference',
      },
      {
        id: 'q2',
        prompt: 'How did the empty room feel?',
        answer: 'Bigger and sadder',
        distractors: ['Smaller and warmer', 'Noisier', 'Exactly the same'],
        explanation: 'The story says the room looked bigger and somehow sadder.',
        skill: 'detail',
      },
      {
        id: 'q3',
        prompt: 'What did Miss Owen say about September?',
        answer: 'New children\'s work would fill it',
        distractors: ['The room would close', 'She was leaving', 'The walls stay bare'],
        explanation: 'She said it would be full of somebody else\'s work in September.',
        skill: 'detail',
      },
    ],
  },
];
