/**
 * Serves the manifest and the packs.
 *
 * There are only two kinds of response here, and their caching is opposite
 * on purpose:
 *
 *   /v1/manifest   mutable, revalidated, ETagged. The one thing a client
 *                  asks for on launch, and usually a 304.
 *   /packs/*       immutable and content-addressed. Cache for a year; a
 *                  changed pack arrives under a different filename.
 *
 * That split is what keeps a launch cheap: one small conditional request,
 * and nothing else unless content actually moved.
 */

import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';

import { Hono } from 'hono';
import { compress } from 'hono/compress';
import { logger } from 'hono/logger';

import type { Manifest } from '../contract';
import { DIST_DIR } from '../bake/config';

/**
 * The manifest is read from disk per request rather than cached in memory,
 * so publishing is "replace the file" and a rollback is "put the old one
 * back" — no restart, no deploy.
 */
function loadManifest(): { manifest: Manifest; body: string; etag: string } | null {
  try {
    const body = readFileSync(join(DIST_DIR, 'manifest.json'), 'utf8');
    return {
      manifest: JSON.parse(body) as Manifest,
      body,
      etag: `"${createHash('sha256').update(body).digest('hex').slice(0, 16)}"`,
    };
  } catch {
    return null;
  }
}

const app = new Hono();

/**
 * Who asked for what. Without this there is no way to tell a device that is
 * quietly failing to update from one that simply has nothing new to fetch —
 * both look like silence.
 */
app.use('*', logger());

// Packs are verbose JSON that gzips about 16:1, so this is the difference
// between a 2MB download and a 90KB one.
app.use('*', compress());

app.get('/healthz', (c) => {
  const loaded = loadManifest();
  return c.json({
    ok: loaded !== null,
    manifestVersion: loaded?.manifest.manifestVersion ?? null,
    packs: loaded?.manifest.packs.length ?? 0,
  }, loaded ? 200 : 503);
});

app.get('/v1/manifest', (c) => {
  const loaded = loadManifest();
  if (!loaded) {
    return c.json({ error: 'no content has been baked yet' }, 503);
  }

  // The client sends back the ETag it stored, so an unchanged manifest costs
  // a header exchange rather than a body.
  if (c.req.header('if-none-match') === loaded.etag) {
    c.header('ETag', loaded.etag);
    c.header('Cache-Control', 'max-age=300, must-revalidate');
    return c.body(null, 304);
  }

  c.header('ETag', loaded.etag);
  c.header('Cache-Control', 'max-age=300, must-revalidate');
  c.header('Content-Type', 'application/json; charset=utf-8');
  return c.body(loaded.body);
});

/**
 * Packs are served by an explicit handler rather than static middleware, so
 * the headers below are guaranteed rather than dependent on a callback the
 * middleware may or may not reach. It also keeps the filename check in one
 * obvious place.
 */
app.get('/packs/:file', (c) => {
  const name = c.req.param('file');

  // Pack names are generated by the bake and always look like
  // "math.g3.a3f9c2b41d08.json" or "rules.a3f9c2b41d08.json". Anything else
  // is not ours, and refusing by shape means no request can walk out of the
  // packs directory.
  if (!/^[a-z]+(\.g[1-5])?\.[0-9a-f]{12}\.json$/.test(name)) {
    return c.json({ error: 'not found' }, 404);
  }

  let body: string;
  try {
    body = readFileSync(join(DIST_DIR, 'packs', name), 'utf8');
  } catch {
    return c.json({ error: 'not found' }, 404);
  }

  // Safe because the filename carries the content hash: different bytes are
  // always a different URL, so nothing here is ever stale.
  c.header('Cache-Control', 'public, max-age=31536000, immutable');
  c.header('Content-Type', 'application/json; charset=utf-8');
  c.header('ETag', `"${name}"`);
  return c.body(body);
});

app.notFound((c) => c.json({ error: 'not found' }, 404));

export { app, loadManifest };
