const { withAndroidManifest, withDangerousMod, AndroidConfig } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

/**
 * Lets the app reach a content server over plain HTTP.
 *
 * Android has blocked cleartext HTTP by default since Android 9. The debug
 * manifest turns it back on so Metro works, but release builds do not get
 * that — so a release build pointed at `http://192.168.x.x:8787` would fail
 * every update check silently, look exactly like a server being down, and
 * quietly run on bundled content for ever.
 *
 * Rather than turning cleartext on for everything, this permits it for
 * exactly the host EXPO_PUBLIC_CONTENT_URL names, and only when that URL is
 * http. Point the app at an https server, or at nothing, and the app is
 * built with no cleartext permission at all.
 *
 * android/ is a generated folder, so this runs at prebuild rather than being
 * a hand-edit the next prebuild would undo.
 */

const CONFIG_NAME = 'content_cleartext';
const CONFIG_RESOURCE = `@xml/${CONFIG_NAME}`;

/** The host of EXPO_PUBLIC_CONTENT_URL, if it is one we need cleartext for. */
function cleartextHost() {
  const url = process.env.EXPO_PUBLIC_CONTENT_URL;
  if (!url) return null;

  let parsed;
  try {
    parsed = new URL(url);
  } catch {
    throw new Error(`EXPO_PUBLIC_CONTENT_URL is not a valid URL: ${url}`);
  }
  // https needs no exemption, which is the whole point of preferring it.
  if (parsed.protocol !== 'http:') return null;
  return parsed.hostname;
}

module.exports = function withContentCleartext(config) {
  const host = cleartextHost();
  if (!host) return config;

  // The rule itself, as an Android network security config resource.
  config = withDangerousMod(config, [
    'android',
    async (config) => {
      const dir = path.join(config.modRequest.platformProjectRoot, 'app/src/main/res/xml');
      fs.mkdirSync(dir, { recursive: true });
      fs.writeFileSync(
        path.join(dir, `${CONFIG_NAME}.xml`),
        `<?xml version="1.0" encoding="utf-8"?>
<!--
  Generated by plugins/withContentCleartext.js from EXPO_PUBLIC_CONTENT_URL.
  Do not edit: android/ is regenerated by prebuild.

  Cleartext is permitted for this one host and nowhere else, so pointing the
  app at a plain-HTTP content server on a home network does not also allow
  unencrypted traffic to the internet at large.
-->
<network-security-config>
  <domain-config cleartextTrafficPermitted="true">
    <domain includeSubdomains="false">${host}</domain>
  </domain-config>
</network-security-config>
`,
        'utf8',
      );
      return config;
    },
  ]);

  // And the reference to it, so the platform actually applies it.
  return withAndroidManifest(config, (config) => {
    const application = AndroidConfig.Manifest.getMainApplicationOrThrow(config.modResults);
    application.$['android:networkSecurityConfig'] = CONFIG_RESOURCE;
    return config;
  });
};
